# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.0
group=com.nyfaria.fancyframes
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Fancy Frames
mod_author=Nyfaria, SirJain0
mod_id=fancyframes
license=ARR
credits=
description=Adds material-based frames to customize paintings and item frames
minecraft_version_range=[1.20, 1.20.2)

neo_form_version=1.21.1-20240808.144430

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.7

# NeoForge
neoforge_version=47.1.3
neoforge_loader_version_range=[2,)
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
forge_config_api_port_version=8.0.3
regutils_version=1.20.1-2.0.3

# Publishing
curseforge_publishing_enabled=true
curseforge_project_id=1430783
modrinth_publishing_enabled=true
modrinth_project_id=hvNGTosJ
dry_run=false