plugins {
    id 'multiloader-loader'
    alias(libs.plugins.mdg.forge)
    alias(libs.plugins.mod.publish)
    alias(libs.plugins.regutils.loader)
}


// Automatically enable neoforge AccessTransformers if the file exists
// This location is hardcoded in FML and can not be changed.
// https://github.com/neoforged/FancyModLoader/blob/a952595eaaddd571fbc53f43847680b00894e0c1/loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModFile.java#L118

legacyForge {
    version = libs.versions.common.minecraft
    def at = project(":common").file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = [at]
    }
    parchment {
        minecraftVersion = libs.versions.parchment.minecraft
        mappingsVersion = libs.versions.parchment.version
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
    runs {
        configureEach {
            jvmArguments =['-XX:+AllowEnhancedClassRedefinition']

        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', rootProject.project(":common").file('src/generated/resources/').getAbsolutePath(), '--existing', rootProject.project(":common").file('src/main/resources/').getAbsolutePath()
        }
    }
}
sourceSets.main.resources { srcDir project(":common").file('src/generated/resources').getAbsolutePath() }

dependencies {

}

publishMods {
    file = jar.archiveFile
    changelog = project(":common").file("changelog.md").text
    type = STABLE
    modLoaders.add("forge")
    displayName = "${mod_name}-${libs.versions.minecraft}-[Forge]-${project.version}"
    dryRun = dry_run.toBoolean()
    if (curseforge_publishing_enabled.toBoolean()) {
        curseforge {
            projectId = curseforge_project_id
            accessToken = curseforge_token
            minecraftVersions.add(libs.versions.minecraft)
            clientRequired = true
            serverRequired = true
            javaVersions.add(JavaVersion.VERSION_17)
        }
    }
    if (modrinth_publishing_enabled.toBoolean()) {
        modrinth {
            accessToken = modrinth_token
            projectId = modrinth_project_id
            minecraftVersions.add(libs.versions.minecraft)
        }
    }
}